# Generated by Django 5.0.1 on 2024-01-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_houses', '0004_property_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
