# Generated by Django 5.0.1 on 2024-01-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_houses', '0005_property_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Rent', 'Rent')], default='Buy', max_length=4),
        ),
    ]
